[[plugins]]
repo = 'loctvl842/monokai-pro.nvim'
hook_add = '''
  nnoremap <Leader>df
  \ <Cmd>Ddu -name=files file_point file_old
  \ `finddir('.git', ';') != '' ? 'file_external' : 'file_rec'`
  \ -sync -ui-param-displaySourceName=short<CR>
  nnoremap <Leader>dg <Cmd>Ddu
  \ -name=search rg
  \ -ui-param-ignoreEmpty
  \ -source-param-input=`input('Pattern: ')`<CR>
  nnoremap <Leader>dp <Cmd>Ddu
  \ -buffer-name=register register
  \ -ui-param-autoResize<CR>
  nnoremap <Leader>dd <Cmd>Ddu
  \ -name=filer-`tabpagenr()` -ui=filer
  \ -source-option-columns=filename file<CR>
'''
