[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = 'mason.nvim'
hook_add = '''
lua << EOF
    local mason = require("mason")
    local mason_lspconfig = require("mason-lspconfig")
    local nvim_lsp = require("lspconfig")

    require("mason").setup({
        ui = {
            icons = {
                package_installed = "✓",
                package_pending = "➜",
                package_uninstalled = "✗"
            }
        }
    })

    mason_lspconfig.setup_handlers({ function(server_name)
        local opts = {}
        opts.on_attach = function (client, bufnr)
            local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
            local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

            local bufopts = { silent = true, buffer = bufnr }
            vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
            vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
            vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
            vim.keymap.set('n', 'gs', vim.lsp.buf.signature_help, bufopts)
            vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
            vim.keymap.set('n', 'gx', vim.lsp.diagnostic.show_line_diagnostics, bufopts)
            vim.keymap.set('n', 'gp', vim.lsp.diagnostic.goto_prev, bufopts)
            vim.keymap.set('n', 'gn', vim.lsp.diagnostic.goto_next, bufopts)
        end
        nvim_lsp[server_name].setup(opts)
    end })
EOF
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
let g:context_filetype#ignore_patterns = {
    \ 'toml': ['^\s*#\s*'],
    \ }
'''

[[plugins]]
repo = 'folke/which-key.nvim'
hook_add = '''
lua << EOF
    require("which-key").setup {
    }
EOF
'''
